services:
  mysql:
    image: mysql:8.0
    container_name: arias_mysql
    environment:
      MYSQL_ROOT_PASSWORD: abcd
      MYSQL_DATABASE: arias_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -pabcd || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30

  api:
    build: .
    container_name: arias_api
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:mysql://arias_mysql:3306/arias_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DB_USER: root
      DB_PASSWORD: abcd
    restart: on-failure   # ðŸ‘ˆ CLAVE

volumes:
  mysql_data:
